name: GitHub Actions
on: [push]
jobs:
  action-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The ${{ github.workspace }} is now ready to test your code on the runner."
      - run: ls ${{ github.workspace }}
      - run: sudo apt update

      - run: echo "start install build tools"
      - run: sudo apt install cargo
      - run: curl https://sh.rustup.rs -sySf | sh
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install cargo-leptos wasm-bindgen-cli
      - run: echo "end install build tools..."

      - run: echo "start build..."
      - run: cargo build --release
      - run: make build
      - run: echo "end build..."
      - run: echo "🍏 This job's status is ${{ job.status }}."
